package co.mgentertainment.file.dal.po;

import java.util.Date;

public class AccessClientDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.id
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.app_code
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.app_name
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.encrypt_algorithm
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private String encryptAlgorithm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.expired_date
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private Date expiredDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.create_time
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.updated_time
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.disabled
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private Byte disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.id
     *
     * @return the value of access_client.id
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.id
     *
     * @param id the value for access_client.id
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.app_code
     *
     * @return the value of access_client.app_code
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.app_code
     *
     * @param appCode the value for access_client.app_code
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.app_name
     *
     * @return the value of access_client.app_name
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.app_name
     *
     * @param appName the value for access_client.app_name
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.encrypt_algorithm
     *
     * @return the value of access_client.encrypt_algorithm
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public String getEncryptAlgorithm() {
        return encryptAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.encrypt_algorithm
     *
     * @param encryptAlgorithm the value for access_client.encrypt_algorithm
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setEncryptAlgorithm(String encryptAlgorithm) {
        this.encryptAlgorithm = encryptAlgorithm == null ? null : encryptAlgorithm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.expired_date
     *
     * @return the value of access_client.expired_date
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public Date getExpiredDate() {
        return expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.expired_date
     *
     * @param expiredDate the value for access_client.expired_date
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.create_time
     *
     * @return the value of access_client.create_time
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.create_time
     *
     * @param createTime the value for access_client.create_time
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.updated_time
     *
     * @return the value of access_client.updated_time
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.updated_time
     *
     * @param updatedTime the value for access_client.updated_time
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_client.disabled
     *
     * @return the value of access_client.disabled
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public Byte getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_client.disabled
     *
     * @param disabled the value for access_client.disabled
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appCode=").append(appCode);
        sb.append(", appName=").append(appName);
        sb.append(", encryptAlgorithm=").append(encryptAlgorithm);
        sb.append(", expiredDate=").append(expiredDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", disabled=").append(disabled);
        sb.append("]");
        return sb.toString();
    }
}