package co.mgentertainment.file.dal.po;

import java.util.Date;

public class ResourceLineDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.line_id
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private Short lineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.line_name
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.provider
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private String provider;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.region
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.bucket
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private String bucket;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.folder
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private String folder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.domain_url
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private String domainUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.priority
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private Short priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.create_time
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.updated_time
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_line.deleted
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.line_id
     *
     * @return the value of resource_line.line_id
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public Short getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.line_id
     *
     * @param lineId the value for resource_line.line_id
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setLineId(Short lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.line_name
     *
     * @return the value of resource_line.line_name
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.line_name
     *
     * @param lineName the value for resource_line.line_name
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setLineName(String lineName) {
        this.lineName = lineName == null ? null : lineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.provider
     *
     * @return the value of resource_line.provider
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public String getProvider() {
        return provider;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.provider
     *
     * @param provider the value for resource_line.provider
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.region
     *
     * @return the value of resource_line.region
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.region
     *
     * @param region the value for resource_line.region
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.bucket
     *
     * @return the value of resource_line.bucket
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public String getBucket() {
        return bucket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.bucket
     *
     * @param bucket the value for resource_line.bucket
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setBucket(String bucket) {
        this.bucket = bucket == null ? null : bucket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.folder
     *
     * @return the value of resource_line.folder
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public String getFolder() {
        return folder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.folder
     *
     * @param folder the value for resource_line.folder
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setFolder(String folder) {
        this.folder = folder == null ? null : folder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.domain_url
     *
     * @return the value of resource_line.domain_url
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public String getDomainUrl() {
        return domainUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.domain_url
     *
     * @param domainUrl the value for resource_line.domain_url
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setDomainUrl(String domainUrl) {
        this.domainUrl = domainUrl == null ? null : domainUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.priority
     *
     * @return the value of resource_line.priority
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public Short getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.priority
     *
     * @param priority the value for resource_line.priority
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setPriority(Short priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.create_time
     *
     * @return the value of resource_line.create_time
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.create_time
     *
     * @param createTime the value for resource_line.create_time
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.updated_time
     *
     * @return the value of resource_line.updated_time
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.updated_time
     *
     * @param updatedTime the value for resource_line.updated_time
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_line.deleted
     *
     * @return the value of resource_line.deleted
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_line.deleted
     *
     * @param deleted the value for resource_line.deleted
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", lineId=").append(lineId);
        sb.append(", lineName=").append(lineName);
        sb.append(", provider=").append(provider);
        sb.append(", region=").append(region);
        sb.append(", bucket=").append(bucket);
        sb.append(", folder=").append(folder);
        sb.append(", domainUrl=").append(domainUrl);
        sb.append(", priority=").append(priority);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }
}