package co.mgentertainment.file.dal.po;

import java.math.BigDecimal;
import java.util.Date;

public class ResourceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.rid
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private Long rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.filename
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.folder
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private String folder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.size
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private BigDecimal size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.type
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.duration
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.create_time
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.updated_time
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.deleted
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.rid
     *
     * @return the value of resource.rid
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.rid
     *
     * @param rid the value for resource.rid
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.filename
     *
     * @return the value of resource.filename
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.filename
     *
     * @param filename the value for resource.filename
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.folder
     *
     * @return the value of resource.folder
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public String getFolder() {
        return folder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.folder
     *
     * @param folder the value for resource.folder
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setFolder(String folder) {
        this.folder = folder == null ? null : folder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.size
     *
     * @return the value of resource.size
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public BigDecimal getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.size
     *
     * @param size the value for resource.size
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setSize(BigDecimal size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.type
     *
     * @return the value of resource.type
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.type
     *
     * @param type the value for resource.type
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.duration
     *
     * @return the value of resource.duration
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.duration
     *
     * @param duration the value for resource.duration
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.create_time
     *
     * @return the value of resource.create_time
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.create_time
     *
     * @param createTime the value for resource.create_time
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.updated_time
     *
     * @return the value of resource.updated_time
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.updated_time
     *
     * @param updatedTime the value for resource.updated_time
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.deleted
     *
     * @return the value of resource.deleted
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.deleted
     *
     * @param deleted the value for resource.deleted
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Wed Sep 20 05:45:12 GST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", filename=").append(filename);
        sb.append(", folder=").append(folder);
        sb.append(", size=").append(size);
        sb.append(", type=").append(type);
        sb.append(", duration=").append(duration);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }
}