package co.mgentertainment.file.dal.po;

import java.math.BigDecimal;

public class ResourceExtDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.rid
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    private Long rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.filename
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.folder
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    private String folder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.size
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    private BigDecimal size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.duration
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.app_code
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.upload_id
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Long uploadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.title
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.type
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.status
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.sub_status
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Short subStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.has_trailer
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Byte hasTrailer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.has_short
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Byte hasShort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.has_cover
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Byte hasCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.trailer_duration
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Integer trailerDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.short_duration
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Integer shortDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.trailer_start_pos
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Integer trailerStartPos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_upload.short_start_pos
     *
     * @mbg.generated Tue Oct 31 06:16:47 GST 2023
     */
    private Integer shortStartPos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.rid
     *
     * @return the value of resource.rid
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.rid
     *
     * @param rid the value for resource.rid
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.filename
     *
     * @return the value of resource.filename
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.filename
     *
     * @param filename the value for resource.filename
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.folder
     *
     * @return the value of resource.folder
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public String getFolder() {
        return folder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.folder
     *
     * @param folder the value for resource.folder
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public void setFolder(String folder) {
        this.folder = folder == null ? null : folder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.size
     *
     * @return the value of resource.size
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public BigDecimal getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.size
     *
     * @param size the value for resource.size
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public void setSize(BigDecimal size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.duration
     *
     * @return the value of resource.duration
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.duration
     *
     * @param duration the value for resource.duration
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.app_code
     *
     * @return the value of resource.app_code
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.app_code
     *
     * @param appCode the value for resource.app_code
     *
     * @mbg.generated Thu Sep 28 17:22:56 GST 2023
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    public Long getUploadId() {
        return uploadId;
    }

    public void setUploadId(Long uploadId) {
        this.uploadId = uploadId;
    }

    public Short getStatus() {
        return status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    public Short getSubStatus() {
        return subStatus;
    }

    public void setSubStatus(Short subStatus) {
        this.subStatus = subStatus;
    }

    public Byte getHasTrailer() {
        return hasTrailer;
    }

    public void setHasTrailer(Byte hasTrailer) {
        this.hasTrailer = hasTrailer;
    }

    public Byte getHasShort() {
        return hasShort;
    }

    public void setHasShort(Byte hasShort) {
        this.hasShort = hasShort;
    }

    public Byte getHasCover() {
        return hasCover;
    }

    public void setHasCover(Byte hasCover) {
        this.hasCover = hasCover;
    }

    public Integer getTrailerDuration() {
        return trailerDuration;
    }

    public void setTrailerDuration(Integer trailerDuration) {
        this.trailerDuration = trailerDuration;
    }

    public Integer getShortDuration() {
        return shortDuration;
    }

    public void setShortDuration(Integer shortDuration) {
        this.shortDuration = shortDuration;
    }

    public Integer getTrailerStartPos() {
        return trailerStartPos;
    }

    public void setTrailerStartPos(Integer trailerStartPos) {
        this.trailerStartPos = trailerStartPos;
    }

    public Integer getShortStartPos() {
        return shortStartPos;
    }

    public void setShortStartPos(Integer shortStartPos) {
        this.shortStartPos = shortStartPos;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Short getType() {
        return type;
    }

    public void setType(Short type) {
        this.type = type;
    }
}