spring:
  application:
    name: mg-file
  profiles:
    active: @env@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: @nacos.server@
        namespace: mg_${spring.profiles.active}
      config:
        server-addr: @nacos.server@
        namespace: file_${spring.profiles.active}
        group: DEFAULT_GROUP
        file-extension: yml
        refresh-enabled: true
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml