package co.mgentertainment.file.service.dto;

import lombok.Data;

@Data
public class AccessClientDTO {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.app_code
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_client.app_name
     *
     * @mbg.generated Thu Sep 28 16:30:26 GST 2023
     */
    private String appName;
}