package co.mgentertainment.file.dal.mapper;

import co.mgentertainment.file.dal.po.AccessClientDO;
import co.mgentertainment.file.dal.po.AccessClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    long countByExample(AccessClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int deleteByExample(AccessClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int insert(AccessClientDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int insertSelective(AccessClientDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    List<AccessClientDO> selectByExample(AccessClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    AccessClientDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int updateByExampleSelective(@Param("row") AccessClientDO row, @Param("example") AccessClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int updateByExample(@Param("row") AccessClientDO row, @Param("example") AccessClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int updateByPrimaryKeySelective(AccessClientDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_client
     *
     * @mbg.generated Thu Sep 21 22:53:08 GST 2023
     */
    int updateByPrimaryKey(AccessClientDO row);
}