package co.mgentertainment.file.dal.mapper;

import co.mgentertainment.file.dal.po.FileUploadDO;

import java.util.List;

public interface FileUploadExtMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Fri Sep 22 01:39:50 GST 2023
     */
    int batchInsert(List<FileUploadDO> rows);
}