package co.mgentertainment.file.dal.mapper;

import co.mgentertainment.file.dal.po.FileUploadDO;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface FileUploadExtMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Fri Sep 22 01:39:50 GST 2023
     */
    int batchInsert(List<FileUploadDO> rows);

    List<FileUploadDO> selectByStatusAndInTime(@Param("statusList") List<Integer> statusList,
                                               @Param("subStatusList") List<Integer> subStatusList,
                                               @Param("deadline") Date deadline);
}