package co.mgentertainment.file.dal.mapper;

import co.mgentertainment.file.dal.po.ResourceLineDO;
import co.mgentertainment.file.dal.po.ResourceLineExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourceLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    long countByExample(ResourceLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int deleteByExample(ResourceLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int deleteByPrimaryKey(Short lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int insert(ResourceLineDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int insertSelective(ResourceLineDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    List<ResourceLineDO> selectByExample(ResourceLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    ResourceLineDO selectByPrimaryKey(Short lineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByExampleSelective(@Param("row") ResourceLineDO row, @Param("example") ResourceLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByExample(@Param("row") ResourceLineDO row, @Param("example") ResourceLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByPrimaryKeySelective(ResourceLineDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_line
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByPrimaryKey(ResourceLineDO row);
}