package co.mgentertainment.file.dal.mapper;

import co.mgentertainment.file.dal.po.ResourceDO;
import co.mgentertainment.file.dal.po.ResourceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    long countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int deleteByPrimaryKey(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int insert(ResourceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int insertSelective(ResourceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    List<ResourceDO> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    ResourceDO selectByPrimaryKey(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByExampleSelective(@Param("row") ResourceDO row, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByExample(@Param("row") ResourceDO row, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByPrimaryKeySelective(ResourceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbg.generated Thu Sep 14 20:49:52 GST 2023
     */
    int updateByPrimaryKey(ResourceDO row);
}