package co.saiyan.file.dal.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FileUploadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public FileUploadExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUploadIdIsNull() {
            addCriterion("upload_id is null");
            return (Criteria) this;
        }

        public Criteria andUploadIdIsNotNull() {
            addCriterion("upload_id is not null");
            return (Criteria) this;
        }

        public Criteria andUploadIdEqualTo(Long value) {
            addCriterion("upload_id =", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotEqualTo(Long value) {
            addCriterion("upload_id <>", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdGreaterThan(Long value) {
            addCriterion("upload_id >", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdGreaterThanOrEqualTo(Long value) {
            addCriterion("upload_id >=", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLessThan(Long value) {
            addCriterion("upload_id <", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLessThanOrEqualTo(Long value) {
            addCriterion("upload_id <=", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdIn(List<Long> values) {
            addCriterion("upload_id in", values, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotIn(List<Long> values) {
            addCriterion("upload_id not in", values, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdBetween(Long value1, Long value2) {
            addCriterion("upload_id between", value1, value2, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotBetween(Long value1, Long value2) {
            addCriterion("upload_id not between", value1, value2, "uploadId");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("filename is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("filename is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("filename =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("filename <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("filename >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("filename >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("filename <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("filename <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("filename like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("filename not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("filename in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("filename not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("filename between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("filename not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Short value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Short value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Short value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Short value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Short value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Short> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Short> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Short value1, Short value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Short value1, Short value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSubStatusIsNull() {
            addCriterion("sub_status is null");
            return (Criteria) this;
        }

        public Criteria andSubStatusIsNotNull() {
            addCriterion("sub_status is not null");
            return (Criteria) this;
        }

        public Criteria andSubStatusEqualTo(Short value) {
            addCriterion("sub_status =", value, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusNotEqualTo(Short value) {
            addCriterion("sub_status <>", value, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusGreaterThan(Short value) {
            addCriterion("sub_status >", value, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("sub_status >=", value, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusLessThan(Short value) {
            addCriterion("sub_status <", value, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusLessThanOrEqualTo(Short value) {
            addCriterion("sub_status <=", value, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusIn(List<Short> values) {
            addCriterion("sub_status in", values, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusNotIn(List<Short> values) {
            addCriterion("sub_status not in", values, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusBetween(Short value1, Short value2) {
            addCriterion("sub_status between", value1, value2, "subStatus");
            return (Criteria) this;
        }

        public Criteria andSubStatusNotBetween(Short value1, Short value2) {
            addCriterion("sub_status not between", value1, value2, "subStatus");
            return (Criteria) this;
        }

        public Criteria andAppCodeIsNull() {
            addCriterion("app_code is null");
            return (Criteria) this;
        }

        public Criteria andAppCodeIsNotNull() {
            addCriterion("app_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppCodeEqualTo(String value) {
            addCriterion("app_code =", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotEqualTo(String value) {
            addCriterion("app_code <>", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeGreaterThan(String value) {
            addCriterion("app_code >", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeGreaterThanOrEqualTo(String value) {
            addCriterion("app_code >=", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeLessThan(String value) {
            addCriterion("app_code <", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeLessThanOrEqualTo(String value) {
            addCriterion("app_code <=", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeLike(String value) {
            addCriterion("app_code like", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotLike(String value) {
            addCriterion("app_code not like", value, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeIn(List<String> values) {
            addCriterion("app_code in", values, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotIn(List<String> values) {
            addCriterion("app_code not in", values, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeBetween(String value1, String value2) {
            addCriterion("app_code between", value1, value2, "appCode");
            return (Criteria) this;
        }

        public Criteria andAppCodeNotBetween(String value1, String value2) {
            addCriterion("app_code not between", value1, value2, "appCode");
            return (Criteria) this;
        }

        public Criteria andRidIsNull() {
            addCriterion("rid is null");
            return (Criteria) this;
        }

        public Criteria andRidIsNotNull() {
            addCriterion("rid is not null");
            return (Criteria) this;
        }

        public Criteria andRidEqualTo(Long value) {
            addCriterion("rid =", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotEqualTo(Long value) {
            addCriterion("rid <>", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThan(Long value) {
            addCriterion("rid >", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThanOrEqualTo(Long value) {
            addCriterion("rid >=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThan(Long value) {
            addCriterion("rid <", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThanOrEqualTo(Long value) {
            addCriterion("rid <=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidIn(List<Long> values) {
            addCriterion("rid in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotIn(List<Long> values) {
            addCriterion("rid not in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidBetween(Long value1, Long value2) {
            addCriterion("rid between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotBetween(Long value1, Long value2) {
            addCriterion("rid not between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andHasTrailerIsNull() {
            addCriterion("has_trailer is null");
            return (Criteria) this;
        }

        public Criteria andHasTrailerIsNotNull() {
            addCriterion("has_trailer is not null");
            return (Criteria) this;
        }

        public Criteria andHasTrailerEqualTo(Byte value) {
            addCriterion("has_trailer =", value, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerNotEqualTo(Byte value) {
            addCriterion("has_trailer <>", value, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerGreaterThan(Byte value) {
            addCriterion("has_trailer >", value, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerGreaterThanOrEqualTo(Byte value) {
            addCriterion("has_trailer >=", value, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerLessThan(Byte value) {
            addCriterion("has_trailer <", value, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerLessThanOrEqualTo(Byte value) {
            addCriterion("has_trailer <=", value, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerIn(List<Byte> values) {
            addCriterion("has_trailer in", values, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerNotIn(List<Byte> values) {
            addCriterion("has_trailer not in", values, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerBetween(Byte value1, Byte value2) {
            addCriterion("has_trailer between", value1, value2, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasTrailerNotBetween(Byte value1, Byte value2) {
            addCriterion("has_trailer not between", value1, value2, "hasTrailer");
            return (Criteria) this;
        }

        public Criteria andHasShortIsNull() {
            addCriterion("has_short is null");
            return (Criteria) this;
        }

        public Criteria andHasShortIsNotNull() {
            addCriterion("has_short is not null");
            return (Criteria) this;
        }

        public Criteria andHasShortEqualTo(Byte value) {
            addCriterion("has_short =", value, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortNotEqualTo(Byte value) {
            addCriterion("has_short <>", value, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortGreaterThan(Byte value) {
            addCriterion("has_short >", value, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortGreaterThanOrEqualTo(Byte value) {
            addCriterion("has_short >=", value, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortLessThan(Byte value) {
            addCriterion("has_short <", value, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortLessThanOrEqualTo(Byte value) {
            addCriterion("has_short <=", value, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortIn(List<Byte> values) {
            addCriterion("has_short in", values, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortNotIn(List<Byte> values) {
            addCriterion("has_short not in", values, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortBetween(Byte value1, Byte value2) {
            addCriterion("has_short between", value1, value2, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasShortNotBetween(Byte value1, Byte value2) {
            addCriterion("has_short not between", value1, value2, "hasShort");
            return (Criteria) this;
        }

        public Criteria andHasCoverIsNull() {
            addCriterion("has_cover is null");
            return (Criteria) this;
        }

        public Criteria andHasCoverIsNotNull() {
            addCriterion("has_cover is not null");
            return (Criteria) this;
        }

        public Criteria andHasCoverEqualTo(Byte value) {
            addCriterion("has_cover =", value, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverNotEqualTo(Byte value) {
            addCriterion("has_cover <>", value, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverGreaterThan(Byte value) {
            addCriterion("has_cover >", value, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverGreaterThanOrEqualTo(Byte value) {
            addCriterion("has_cover >=", value, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverLessThan(Byte value) {
            addCriterion("has_cover <", value, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverLessThanOrEqualTo(Byte value) {
            addCriterion("has_cover <=", value, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverIn(List<Byte> values) {
            addCriterion("has_cover in", values, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverNotIn(List<Byte> values) {
            addCriterion("has_cover not in", values, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverBetween(Byte value1, Byte value2) {
            addCriterion("has_cover between", value1, value2, "hasCover");
            return (Criteria) this;
        }

        public Criteria andHasCoverNotBetween(Byte value1, Byte value2) {
            addCriterion("has_cover not between", value1, value2, "hasCover");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationIsNull() {
            addCriterion("trailer_duration is null");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationIsNotNull() {
            addCriterion("trailer_duration is not null");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationEqualTo(Integer value) {
            addCriterion("trailer_duration =", value, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationNotEqualTo(Integer value) {
            addCriterion("trailer_duration <>", value, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationGreaterThan(Integer value) {
            addCriterion("trailer_duration >", value, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("trailer_duration >=", value, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationLessThan(Integer value) {
            addCriterion("trailer_duration <", value, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationLessThanOrEqualTo(Integer value) {
            addCriterion("trailer_duration <=", value, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationIn(List<Integer> values) {
            addCriterion("trailer_duration in", values, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationNotIn(List<Integer> values) {
            addCriterion("trailer_duration not in", values, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationBetween(Integer value1, Integer value2) {
            addCriterion("trailer_duration between", value1, value2, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("trailer_duration not between", value1, value2, "trailerDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationIsNull() {
            addCriterion("short_duration is null");
            return (Criteria) this;
        }

        public Criteria andShortDurationIsNotNull() {
            addCriterion("short_duration is not null");
            return (Criteria) this;
        }

        public Criteria andShortDurationEqualTo(Integer value) {
            addCriterion("short_duration =", value, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationNotEqualTo(Integer value) {
            addCriterion("short_duration <>", value, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationGreaterThan(Integer value) {
            addCriterion("short_duration >", value, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("short_duration >=", value, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationLessThan(Integer value) {
            addCriterion("short_duration <", value, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationLessThanOrEqualTo(Integer value) {
            addCriterion("short_duration <=", value, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationIn(List<Integer> values) {
            addCriterion("short_duration in", values, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationNotIn(List<Integer> values) {
            addCriterion("short_duration not in", values, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationBetween(Integer value1, Integer value2) {
            addCriterion("short_duration between", value1, value2, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andShortDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("short_duration not between", value1, value2, "shortDuration");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosIsNull() {
            addCriterion("trailer_start_pos is null");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosIsNotNull() {
            addCriterion("trailer_start_pos is not null");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosEqualTo(Integer value) {
            addCriterion("trailer_start_pos =", value, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosNotEqualTo(Integer value) {
            addCriterion("trailer_start_pos <>", value, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosGreaterThan(Integer value) {
            addCriterion("trailer_start_pos >", value, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosGreaterThanOrEqualTo(Integer value) {
            addCriterion("trailer_start_pos >=", value, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosLessThan(Integer value) {
            addCriterion("trailer_start_pos <", value, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosLessThanOrEqualTo(Integer value) {
            addCriterion("trailer_start_pos <=", value, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosIn(List<Integer> values) {
            addCriterion("trailer_start_pos in", values, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosNotIn(List<Integer> values) {
            addCriterion("trailer_start_pos not in", values, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosBetween(Integer value1, Integer value2) {
            addCriterion("trailer_start_pos between", value1, value2, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andTrailerStartPosNotBetween(Integer value1, Integer value2) {
            addCriterion("trailer_start_pos not between", value1, value2, "trailerStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosIsNull() {
            addCriterion("short_start_pos is null");
            return (Criteria) this;
        }

        public Criteria andShortStartPosIsNotNull() {
            addCriterion("short_start_pos is not null");
            return (Criteria) this;
        }

        public Criteria andShortStartPosEqualTo(Integer value) {
            addCriterion("short_start_pos =", value, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosNotEqualTo(Integer value) {
            addCriterion("short_start_pos <>", value, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosGreaterThan(Integer value) {
            addCriterion("short_start_pos >", value, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosGreaterThanOrEqualTo(Integer value) {
            addCriterion("short_start_pos >=", value, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosLessThan(Integer value) {
            addCriterion("short_start_pos <", value, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosLessThanOrEqualTo(Integer value) {
            addCriterion("short_start_pos <=", value, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosIn(List<Integer> values) {
            addCriterion("short_start_pos in", values, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosNotIn(List<Integer> values) {
            addCriterion("short_start_pos not in", values, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosBetween(Integer value1, Integer value2) {
            addCriterion("short_start_pos between", value1, value2, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andShortStartPosNotBetween(Integer value1, Integer value2) {
            addCriterion("short_start_pos not between", value1, value2, "shortStartPos");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Byte value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Byte value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Byte value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Byte value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Byte> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Byte> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Byte value1, Byte value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_upload
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 16 05:47:02 GST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table file_upload
     *
     * @mbg.generated Thu Nov 16 05:47:02 GST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}